# ============================================
# docker-compose.yml
# ============================================
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: senmarket_postgres
    environment:
      POSTGRES_DB: senmarket
      POSTGRES_USER: senmarket
      POSTGRES_PASSWORD: senmarket123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - senmarket

  redis:
    image: redis:7-alpine
    container_name: senmarket_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - senmarket

  minio:
    image: minio/minio:latest
    container_name: senmarket_minio
    environment:
      MINIO_ROOT_USER: senmarket
      MINIO_ROOT_PASSWORD: senmarket123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - senmarket

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: senmarket_app
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - senmarket

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  senmarket:
    driver: bridge